/// Every command registered in `lib.rs`'s `invoke_handler!`.
///
/// Declaring these turns the app-level ACL ON (`has_app_acl_manifest`). Until
/// it is on, Tauri skips the capability check for app-defined commands
/// entirely, so `capabilities/default.json`'s `"windows": ["main"]` scoping
/// does nothing and the remote login webview (label `platform-login`) can
/// invoke every command — including `read_cookies_file`.
///
/// KEEP IN SYNC WITH `invoke_handler!`: a command missing here gets no
/// autogenerated `allow-*` permission, so the main window is denied it at
/// runtime (the failure is silent until that command is called).
const APP_COMMANDS: &[&str] = &[
    "detect_file",
    "convert_file",
    "cancel_conversion",
    "resize_image",
    "download_from_url",
    "cancel_download",
    "probe_url",
    "http_request",
    "download_direct",
    "read_cookies_file",
    "write_cookies_file",
    "cookies_file_path",
    "file_exists",
    "open_login_window",
    "set_keep_awake",
    "read_file_binary",
    "fetch_remote_image",
    "open_file",
    "open_in_folder",
    "download_installer",
    "launch_installer",
    "ensure_tools",
    "tools_ready",
    "update_ytdlp",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
